apiVersion: v1
kind: Service
metadata:
  name: {{ include "mailhog-stunnel.fullname" . }}
  labels:
    {{- include "mailhog-stunnel.labels" . | nindent 4 }}
spec:
  type: {{ .Values.mailhog.service.type }}
  ports:
    - port: {{ .Values.mailhog.service.http }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.mailhog.service.smtp }}
      targetPort: tcp-smtp
      protocol: TCP
      name: smtp
  selector:
    {{- include "mailhog-stunnel.selectorLabels" . | nindent 4 }}
